# Generated by Django 2.1.1 on 2018-09-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BowenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bTitle', models.CharField(max_length=30)),
                ('bPic', models.ImageField(upload_to='bowen_img')),
                ('bContent', models.CharField(max_length=130)),
                ('bDate', models.DateTimeField(auto_now_add=True)),
                ('bClick', models.IntegerField()),
                ('bComment', models.IntegerField()),
                ('bIsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tTitle', models.CharField(max_length=20)),
                ('tIsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
