# Generated by Django 2.1.1 on 2018-09-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boweninfo',
            name='bClick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boweninfo',
            name='bComment',
            field=models.IntegerField(default=0),
        ),
    ]
