# Generated by Django 2.1.1 on 2018-09-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180921_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boweninfo',
            name='bPic',
            field=models.ImageField(blank=True, upload_to='bowen_img'),
        ),
    ]
