# Generated by Django 2.1.1 on 2018-09-21 04:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180921_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='boweninfo',
            name='bType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.TypeInfo'),
        ),
        migrations.AlterField(
            model_name='boweninfo',
            name='bContent',
            field=tinymce.models.HTMLField(),
        ),
    ]
