# Generated by Django 2.1.1 on 2018-09-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180921_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='boweninfo',
            name='bIstop',
            field=models.BooleanField(default=False),
        ),
    ]
