# Generated by Django 2.1.1 on 2018-09-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=20)),
                ('uPhone', models.CharField(max_length=20)),
                ('uEmail', models.CharField(max_length=20)),
                ('uPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
